### ISSUE TITLE
[AVIS?] Info phobies

### ISSUE THREAD

**Issue by LiseFa** [m2dimi/kls-phobia#9]
J'ai crée un nouveau dossier dans le drive "Elements graphiques"

J'ai mis dedans des essais pour :
- la timeline
- la représentation graphique "traumatisme" ou "inconnu" sur les phobies
- infobulle des phobies

**Comment by ghost** [comment]
Pas mal ! As-tu des news pour les niveaux gifs ? (Attention : bien penser à éviter le fond transparent !)
Merciiiiiiii
